### ISSUE TITLE
скрипт не стартует

### ISSUE THREAD

**Issue by ya4ept** [LookiMan/EXE2PY-Decompiler#2]
Python 3.8.6rc1
скрипт не стартует, появляется ошибка:
```css
.\EXE2PY-Decompiler>Decompiler.py
Traceback (most recent call last):
  File ".\EXE2PY-Decompiler\Decompiler.py", line 35, in <module>
    from uncompyle6.bin import uncompile
  File "C:\python3\lib\site-packages\uncompyle6\__init__.py", line 53, in <module>
    import uncompyle6.semantics.pysource
  File "C:\python3\lib\site-packages\uncompyle6\semantics\pysource.py", line 141, in <module>
    from uncompyle6.parsers.treenode import SyntaxTree
  File "C:\python3\lib\site-packages\uncompyle6\parsers\treenode.py", line 3, in <module>
    from uncompyle6.scanners.tok import NoneToken
  File "C:\python3\lib\site-packages\uncompyle6\scanners\tok.py", line 200, in <module>
    NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
  File "C:\python3\lib\site-packages\uncompyle6\scanners\tok.py", line 86, in __init__
    from xdis.std import _std_api
  File "C:\python3\lib\site-packages\xdis\std.py", line 220, in <module>
    _std_api = make_std_api()
  File "C:\python3\lib\site-packages\xdis\std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
  File "C:\python3\lib\site-packages\xdis\std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "C:\python3\lib\site-packages\xdis\op_imports.py", line 170, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '3.8.6candidate1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\EXE2PY-Decompiler\Decompiler.py", line 37, in <module>
    showerror(exc.msg)
AttributeError: 'KeyError' object has no attribute 'msg'
```

**Comment by LookiMan** [comment]
Наверное, проблема в вашей версии python

**Comment by webguru0110** [comment]
(.venv) PS D:\EXE2PY-Decompiler> python .\main.py        
qt.qpa.fonts: Unable to open default EUDC font: "EUDC.TTE"
Traceback (most recent call last):
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\load.py", line 308, in load_module_from_file_object
    co = xdis.unmarshal.load_code(fp, magic_int, code_objects)
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\unmarshal.py", line 637, in load_code
    return um_gen.load()
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\unmarshal.py", line 180, in load
    return self.r_object()
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\unmarshal.py", line 224, in r_object
    return unmarshal_func(save_ref, bytes_for_s)
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\unmarshal.py", line 524, in t_code
    co_consts = self.r_object(bytes_for_s=bytes_for_s)
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\unmarshal.py", line 224, in r_object
    return unmarshal_func(save_ref, bytes_for_s)
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\unmarshal.py", line 385, in t_small_tuple
    ret += (self.r_object(bytes_for_s=bytes_for_s),)
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\unmarshal.py", line 224, in r_object
    return unmarshal_func(save_ref, bytes_for_s)
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\unmarshal.py", line 524, in t_code
    co_consts = self.r_object(bytes_for_s=bytes_for_s)
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\unmarshal.py", line 224, in r_object
    return unmarshal_func(save_ref, bytes_for_s)
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\unmarshal.py", line 385, in t_small_tuple
    ret += (self.r_object(bytes_for_s=bytes_for_s),)
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\unmarshal.py", line 224, in r_object
    return unmarshal_func(save_ref, bytes_for_s)
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\unmarshal.py", line 590, in t_code
    code = to_portable(
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\codetype\__init__.py", line 230, in to_portable
    return codeType2Portable(code, version_triple)
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\codetype\__init__.py", line 45, in codeType2Portable
    return Code3(
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\codetype\code30.py", line 84, in __init__
    self.check()
  File "D:\EXE2PY-Decompiler\.venv\lib\site-packages\xdis\codetype\code13.py", line 78, in check
    assert (
AssertionError: co_freevars should be one of the types (<class 'tuple'>, <class 'list'>); is type <class 'bytes'>
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
