### ISSUE TITLE
I get error

### ISSUE THREAD

**Issue by antimagetiny** [LookiMan/EXE2PY-Decompiler#6]
Traceback (most recent call last):
  File "D:\EXE2PY-Decompiler-master\main.py", line 478, in <module>
    main()
  File "D:\EXE2PY-Decompiler-master\main.py", line 457, in main
    widget = MainWindow(start_decompile)
  File "D:\EXE2PY-Decompiler-master\ui.py", line 323, in __init__
    self._customize_window()
  File "D:\EXE2PY-Decompiler-master\ui.py", line 274, in _customize_window
    self.header = Header(self.form)
  File "D:\EXE2PY-Decompiler-master\ui.py", line 246, in __init__
    self.title = Title(parent, parent.width() * 0.8, self._height)
  File "D:\EXE2PY-Decompiler-master\ui.py", line 195, in __init__
    self.setGeometry(QtCore.QRect(10, 0, self._width, self._height))
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(aleft: int, atop: int, awidth: int, aheight: int): argument 3 has unexpected type 'float'
  QRect(atopLeft: QPoint, abottomRight: QPoint): argument 1 has unexpected type 'int'
  QRect(atopLeft: QPoint, asize: QSize): argument 1 has unexpected type 'int'
  QRect(a0: QRect): argument 1 has unexpected type 'int'

**Comment by LookiMan** [comment]
The TypeError occurred due to float values being passed to QRect during widget initialization. This has been fixed by converting the float values to integers before passing them as arguments.

Resolution:
To resolve this issue, simply pull the latest changes from the master branch, where the fix has been applied.
